### ISSUE TITLE
Is the Rust client ready for use?

### ISSUE THREAD

**Issue by d4h0** [vesoft-inc/nebula-rust#12]
Hi,

I'm wondering if this crate is already ready for use.

There isn't any indicator in the README that this is "Work-In-Progress", but there isn't a usable version on [crates.io](https://crates.io/crates/nebula-rust) either.

If the client isn't ready: Is there any estimate when it will be usable?

I'd love to give Nebula a try! :)

**Comment by wey-gu** [comment]
Dear @Shylock-Hg,
We are in the shape of changing license and pushing to crates(other than new version uplift work), or?
Thanks

**Comment by Shylock-Hg** [comment]
Hello, d4h0. It's not ready now. @Sophie-Xie Do we have to plan to do this?

**Comment by Sophie-Xie** [comment]
> Hello, d4h0. It's not ready now. @Sophie-Xie Do we have to plan to do this?

Recently we have some other more important things to do, so have no plans now.

**Comment by wey-gu** [comment]
@Shylock-Hg how much effort is left for nebula-rust ready to use, please? It's only blocked by license issue or actually still missing quite some jobs to be done?

**Comment by Shylock-Hg** [comment]
> @Shylock-Hg how much effort is left for nebula-rust ready to use, please? It's only blocked by license issue or actually still missing quite some jobs to be done?

A lot of work to update to nebula now.

**Comment by d4h0** [comment]
Thanks everybody, for the fast response!

Maybe a short notice at the top of the README would be useful to communicate the current state of the package? Because with Rust we can install packages directly from GitHub (similar to Go, I believe). This would prevent potential users from installing an unfinished Nebula client (which could lead to a bad experience for this potential user).

**Comment by Shylock-Hg** [comment]
> Thanks everybody, for the fast response!
> 
> Maybe a short notice at the top of the README would be useful to communicate the current state of the package? Because with Rust we can install packages directly from GitHub (similar to Go, I believe). This would prevent potential users from installing an unfinished Nebula client (which could lead to a bad experience for this potential user).

Yes, I will add.

**Comment by d4h0** [comment]
Thank you, I think this issue can be closed now.
