### ISSUE TITLE
Add credit to upstream/fork source of the great vkill

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-rust#19]
@WW-SONG (with @Milittle ) had been working on NebulaGraph Rust client on the great work started by @vkill under https://github.com/bk-rs/nebula-rs

We need to highlight all those authors in this repo and describe the relationship between this repo and @vkill's projects.

**Comment by Milittle** [comment]
We've included a reference to @vkill's project in our README.

From here
https://github.com/vesoft-inc/nebula-rust#reference

**Comment by wey-gu** [comment]
> We've included a reference to @vkill's project in our README.
> 
> From here https://github.com/vesoft-inc/nebula-rust#reference

Oh, sorry I missed the reference section of the README!
